language: php
php:
    - 7.1
    - 7.2
    - 7.3
matrix:
    allow_failures:
        - php: hhvm

script: vendor/bin/tester tests -s -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source
